# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    # Define the sms gateway parameters
    sms_gateway.baseurl: '%env(resolve:SMSGATEWAY_BASEURL)%'
    sms_gateway.apikey: '%env(resolve:SMSGATEWAY_APIKEY)%'
    sms_gateway.apikeyprefix: '%env(resolve:SMSGATEWAY_APIKEYPREFIX)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%kernel.project_dir%/public/uploads'
    monolog.dbhandler:
        class: App\Utility\DbHandler

#    App\Controller\SecurityController:
#        arguments: ['@monolog.logger.db']
    monolog.dbprocessor:
        class: App\Utility\DbProcessor
        tags:
            - {name: monolog.processor,handler: dbhandler }
    doctrine.doctrinesubscriber:
        class: App\EventListener\DoctrineSubscriber
        tags:
            -   {name: doctrine.event_subscriber}
    App\Service\CustomLoginLinkHandler:
        arguments:
            $urlGenerator: '@router'
            $userProvider: '@security.user_providers' # Assurez-vous de remplacer par votre provider utilisateur
        tags: [ 'security.login_link_handler' ]
    App\EventSubscriber\LoginSubscriber:
        tags:
            - { name: kernel.event_subscriber }